NUM_NODES = 10
VECTORS_PER_NODE = 1000
SUBSET_SIZE = NUM_NODES * VECTORS_PER_NODE
REPLICATION = True
EARLY_STOP_ENABLED = False
EARLY_STOP_THRESHOLD = 44000.0
EVAL_VARIANT = "both"
ROUTING_FANOUT = 2

TOXIPROXY_ENABLED = True
TOXIPROXY_HOST = '127.0.0.1'
TOXIPROXY_API_PORT = 8474
REAL_PORT_START = 5000
PROXY_PORT_START = 6000
TOXIC_LATENCY_MS = 0
TOXIC_LATENCY_JITTER_MS = 0
TOXIC_PACKET_LOSS_PCT = 0.0    

FAULT_INJECTION_ENABLED = False
FAULT_KILL_INTERVAL = 10.0
FAULT_KILL_PROBABILITY = 0.3
FAULT_MAX_DOWN = 3
FAULT_RESTART_DELAY = 8.0
FAULT_SEED = 42