NUM_NODES = 20
VECTORS_PER_NODE = 1000
SUBSET_SIZE = NUM_NODES * VECTORS_PER_NODE
REPLICATION = True
PLACEMENT = 'clustered'
EARLY_STOP_ENABLED = False
EARLY_STOP_THRESHOLD = 65000.0
ROUTING_FANOUT = 2
ROUTING_STRATEGY = 'greedy' # 'greedy' oder 'random' oder 'flood' oder 'iterative'
ROUTING_ALPHA = 3
ROUTING_EF = 16
ROUTING_DEBUG = False

DATASET = 'sift' # 'sift' oder 'ir'
DIMENSION = 128 if DATASET == 'sift' else 384
MAX_NEIGHBORS = 8
HNSW_M = 32

GOSSIP_INTERVAL_S = 5
HEALTH_CHECK_INTERVAL_S = 5
RPC_TIMEOUT_S = 1.5
RPC_TIMEOUT_BASE_S = 1.5
PING_TIMEOUT_S = 1.0

NUM_QUERIES = 300
NUM_RUNS = 5
K = 3
TTL_VALUES = [4, 6]
GOSSIP_WARMUP_S = 30

LATENCY_PRESETS = {
    "none":             (0,   0),
    "lan":              (1,   1),
    "same_region":      (5,   2),
    "same_continent":   (30,  10),
    "intercontinental": (100, 30),
    "mobile":           (150, 80),
}
LATENCY_SCENARIO = 'none'

TOXIPROXY_ENABLED = False
TOXIPROXY_HOST = '127.0.0.1'
TOXIPROXY_API_PORT = 8474
REAL_PORT_START = 5000
PROXY_PORT_START = 6000
TOXIC_LATENCY_MS = 0
TOXIC_LATENCY_JITTER_MS = 0
TOXIC_CONN_DROP_PCT = 0.0

SEED = 1234         

FAULT_INJECTION_ENABLED = False
FAULT_KILL_INTERVAL = 10.0
FAULT_KILL_PROBABILITY = 0.3
FAULT_MAX_DOWN = 0
FAULT_RESTART_DELAY = 8.0
FAULT_SEED = 42